default: &default
  host: localhost
  adapter: postgresql
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: activeadmin-api_development

test:
  <<: *default
  database: activeadmin-api_test

production:
  <<: *default
  database: activeadmin-api_production
